title:              Natnael Mogos
email:              natumogos@googlemail.com
description:        M.Sc. Nanoscience graduate, programmer and AI enthusiast.
author:             Natnael Mogos
baseurl:            ""
url:                "https://NatnaelMogos.github.io"

# Social Profiles
twitter_username:   
github_username:    NatnaelMogos
facebook_username:  
instagram_username:  
linkedin_username: natnael-mogos-935181222	

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
